//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailizrClient.AdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cocktail", Namespace="http://schemas.datacontract.org/2004/07/Cocktailizr.Model.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<decimal, CocktailizrClient.AdminServiceReference.Zutat>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CocktailizrClient.AdminServiceReference.Color))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CocktailizrClient.AdminServiceReference.Rezept))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CocktailizrClient.AdminServiceReference.Step[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CocktailizrClient.AdminServiceReference.Step))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CocktailizrClient.AdminServiceReference.Zutat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CocktailizrClient.AdminServiceReference.ZutatenSkala))]
    public partial class Cocktail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlcoholicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CocktailizrClient.AdminServiceReference.Color DrinkColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CocktailizrClient.AdminServiceReference.Rezept RezeptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<decimal, CocktailizrClient.AdminServiceReference.Zutat> ZutatenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alcoholic {
            get {
                return this.AlcoholicField;
            }
            set {
                if ((this.AlcoholicField.Equals(value) != true)) {
                    this.AlcoholicField = value;
                    this.RaisePropertyChanged("Alcoholic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CocktailizrClient.AdminServiceReference.Color DrinkColor {
            get {
                return this.DrinkColorField;
            }
            set {
                if ((this.DrinkColorField.Equals(value) != true)) {
                    this.DrinkColorField = value;
                    this.RaisePropertyChanged("DrinkColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CocktailizrClient.AdminServiceReference.Rezept Rezept {
            get {
                return this.RezeptField;
            }
            set {
                if ((object.ReferenceEquals(this.RezeptField, value) != true)) {
                    this.RezeptField = value;
                    this.RaisePropertyChanged("Rezept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<decimal, CocktailizrClient.AdminServiceReference.Zutat> Zutaten {
            get {
                return this.ZutatenField;
            }
            set {
                if ((object.ReferenceEquals(this.ZutatenField, value) != true)) {
                    this.ZutatenField = value;
                    this.RaisePropertyChanged("Zutaten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    [System.SerializableAttribute()]
    public partial struct Color : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short knownColorField;
        
        private string nameField;
        
        private short stateField;
        
        private long valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short knownColor {
            get {
                return this.knownColorField;
            }
            set {
                if ((this.knownColorField.Equals(value) != true)) {
                    this.knownColorField = value;
                    this.RaisePropertyChanged("knownColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rezept", Namespace="http://schemas.datacontract.org/2004/07/Cocktailizr.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class Rezept : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CocktailizrClient.AdminServiceReference.Step[] ZubereitungsSchritteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ZubereitungszeitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CocktailizrClient.AdminServiceReference.Step[] ZubereitungsSchritte {
            get {
                return this.ZubereitungsSchritteField;
            }
            set {
                if ((object.ReferenceEquals(this.ZubereitungsSchritteField, value) != true)) {
                    this.ZubereitungsSchritteField = value;
                    this.RaisePropertyChanged("ZubereitungsSchritte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Zubereitungszeit {
            get {
                return this.ZubereitungszeitField;
            }
            set {
                if ((this.ZubereitungszeitField.Equals(value) != true)) {
                    this.ZubereitungszeitField = value;
                    this.RaisePropertyChanged("Zubereitungszeit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zutat", Namespace="http://schemas.datacontract.org/2004/07/Cocktailizr.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class Zutat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOptionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CocktailizrClient.AdminServiceReference.ZutatenSkala SkalaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOptional {
            get {
                return this.IsOptionalField;
            }
            set {
                if ((this.IsOptionalField.Equals(value) != true)) {
                    this.IsOptionalField = value;
                    this.RaisePropertyChanged("IsOptional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CocktailizrClient.AdminServiceReference.ZutatenSkala Skala {
            get {
                return this.SkalaField;
            }
            set {
                if ((this.SkalaField.Equals(value) != true)) {
                    this.SkalaField = value;
                    this.RaisePropertyChanged("Skala");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Step", Namespace="http://schemas.datacontract.org/2004/07/Cocktailizr.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class Step : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeschreibungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadlineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beschreibung {
            get {
                return this.BeschreibungField;
            }
            set {
                if ((object.ReferenceEquals(this.BeschreibungField, value) != true)) {
                    this.BeschreibungField = value;
                    this.RaisePropertyChanged("Beschreibung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Headline {
            get {
                return this.HeadlineField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadlineField, value) != true)) {
                    this.HeadlineField = value;
                    this.RaisePropertyChanged("Headline");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZutatenSkala", Namespace="http://schemas.datacontract.org/2004/07/Cocktailizr.Model.Entities")]
    public enum ZutatenSkala : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cl = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Liter = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stueck = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gramm = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Priese = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddCocktail", ReplyAction="http://tempuri.org/IAdminService/AddCocktailResponse")]
        bool AddCocktail(CocktailizrClient.AdminServiceReference.Cocktail cocktail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddCocktail", ReplyAction="http://tempuri.org/IAdminService/AddCocktailResponse")]
        System.Threading.Tasks.Task<bool> AddCocktailAsync(CocktailizrClient.AdminServiceReference.Cocktail cocktail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/ModifyCocktail", ReplyAction="http://tempuri.org/IAdminService/ModifyCocktailResponse")]
        bool ModifyCocktail(System.Guid cocktailId, CocktailizrClient.AdminServiceReference.Cocktail cocktail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/ModifyCocktail", ReplyAction="http://tempuri.org/IAdminService/ModifyCocktailResponse")]
        System.Threading.Tasks.Task<bool> ModifyCocktailAsync(System.Guid cocktailId, CocktailizrClient.AdminServiceReference.Cocktail cocktail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/RemoveCocktail", ReplyAction="http://tempuri.org/IAdminService/RemoveCocktailResponse")]
        bool RemoveCocktail(System.Guid cocktailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/RemoveCocktail", ReplyAction="http://tempuri.org/IAdminService/RemoveCocktailResponse")]
        System.Threading.Tasks.Task<bool> RemoveCocktailAsync(System.Guid cocktailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddZutat", ReplyAction="http://tempuri.org/IAdminService/AddZutatResponse")]
        bool AddZutat(CocktailizrClient.AdminServiceReference.Zutat zutat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddZutat", ReplyAction="http://tempuri.org/IAdminService/AddZutatResponse")]
        System.Threading.Tasks.Task<bool> AddZutatAsync(CocktailizrClient.AdminServiceReference.Zutat zutat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/ModifyZutat", ReplyAction="http://tempuri.org/IAdminService/ModifyZutatResponse")]
        bool ModifyZutat(System.Guid zutatId, CocktailizrClient.AdminServiceReference.Zutat zutat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/ModifyZutat", ReplyAction="http://tempuri.org/IAdminService/ModifyZutatResponse")]
        System.Threading.Tasks.Task<bool> ModifyZutatAsync(System.Guid zutatId, CocktailizrClient.AdminServiceReference.Zutat zutat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/RemoveZutat", ReplyAction="http://tempuri.org/IAdminService/RemoveZutatResponse")]
        bool RemoveZutat(System.Guid zutatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/RemoveZutat", ReplyAction="http://tempuri.org/IAdminService/RemoveZutatResponse")]
        System.Threading.Tasks.Task<bool> RemoveZutatAsync(System.Guid zutatId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : CocktailizrClient.AdminServiceReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<CocktailizrClient.AdminServiceReference.IAdminService>, CocktailizrClient.AdminServiceReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCocktail(CocktailizrClient.AdminServiceReference.Cocktail cocktail) {
            return base.Channel.AddCocktail(cocktail);
        }
        
        public System.Threading.Tasks.Task<bool> AddCocktailAsync(CocktailizrClient.AdminServiceReference.Cocktail cocktail) {
            return base.Channel.AddCocktailAsync(cocktail);
        }
        
        public bool ModifyCocktail(System.Guid cocktailId, CocktailizrClient.AdminServiceReference.Cocktail cocktail) {
            return base.Channel.ModifyCocktail(cocktailId, cocktail);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyCocktailAsync(System.Guid cocktailId, CocktailizrClient.AdminServiceReference.Cocktail cocktail) {
            return base.Channel.ModifyCocktailAsync(cocktailId, cocktail);
        }
        
        public bool RemoveCocktail(System.Guid cocktailId) {
            return base.Channel.RemoveCocktail(cocktailId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveCocktailAsync(System.Guid cocktailId) {
            return base.Channel.RemoveCocktailAsync(cocktailId);
        }
        
        public bool AddZutat(CocktailizrClient.AdminServiceReference.Zutat zutat) {
            return base.Channel.AddZutat(zutat);
        }
        
        public System.Threading.Tasks.Task<bool> AddZutatAsync(CocktailizrClient.AdminServiceReference.Zutat zutat) {
            return base.Channel.AddZutatAsync(zutat);
        }
        
        public bool ModifyZutat(System.Guid zutatId, CocktailizrClient.AdminServiceReference.Zutat zutat) {
            return base.Channel.ModifyZutat(zutatId, zutat);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyZutatAsync(System.Guid zutatId, CocktailizrClient.AdminServiceReference.Zutat zutat) {
            return base.Channel.ModifyZutatAsync(zutatId, zutat);
        }
        
        public bool RemoveZutat(System.Guid zutatId) {
            return base.Channel.RemoveZutat(zutatId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveZutatAsync(System.Guid zutatId) {
            return base.Channel.RemoveZutatAsync(zutatId);
        }
    }
}
